#define MAX_ARROW_SPEED_X -18
#define MAX_ARROW_SPEED_Y -21.6

// ARCHER
#define ARCHER_BASIC_FRAME_WIDTH 113
#define ARCHER_BASIC_FRAME_HEIGHT 187
#define ARCHER_FIRE_FRAME_WIDTH 137
#define TOTAL_WALK_FRAMES 7
#define TOTAL_STAND_FRAME 5
#define TOTAL_FIRE_FRAMES 6

// KNIGHT
#define KNIGHT_RUN_FRAME_WIDTH 58
#define KNIGHT_RUN_FRAME_HEIGHT 66
#define KNIGHT_RUN_ATTACK_FRAME_WIDTH 68
#define KNIGHT_RUN_ATTACK_FRAME_HEIGHT 78
#define KNIGHT_TOTAL_RUN_FRAME 7
#define KNIGHT_TOTAL_RUN_ATTACK_FRAME 6 

// HOT AIR BALLOON
#define HOT_AIR_BALLOON_BOMB_WIDTH 88
#define HOT_AIR_BALLOON_BOMB_HEIGHT 80
#define HOT_AIR_BALLOON_BOMB_TOTALFRAMES 4

// WOLF
#define WOLF_TOTAL_RUN_FRAMES 9
#define WOLF_TOTAL_ATTACK_FRAMES 4
#define WOLF_RUN_WIDTH 120
#define WOLF_RUN_HEIGHT 90
#define WOLF_ATTACK_WIDTH 100
#define WOLF_ATTACK_HEIGHT 86