#define ARCHER_BASIC_FRAME_WIDTH 113
#define ARCHER_BASIC_FRAME_HEIGHT 187
#define ARCHER_FIRE_FRAME_WIDTH 137
#define TOTAL_WALK_FRAMES 7
#define TOTAL_STAND_FRAME 5
#define TOTAL_FIRE_FRAMES 6
#define MAX_ARROW_SPEED_X -18
#define MAX_ARROW_SPEED_Y -21.6